### ISSUE TITLE
[BUG] Authentication error download_gdrive_if_missing

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/fistools#54]
**Welke functie/dataset**
download_gdrive_if_missing

**Beschrijf de bug**
Wanneer @RuttenAnneleen de functie gebruikt om een bestand te downloaden van gdrive krijgt ze onderstaande error:

@RuttenAnneleen hang je je error message hier ?

**Stappen om de bug te reproduceren:**
Voeg hier een stuk code in om de fout te reproduceren

**Verwachte uikomst**
@RuttenAnneleen kan de functie gebruiken en iemand anders ook.
=> voeg documentatie toe om de bug te fixen.

**Screenshots**
Indien van toepassing

**Extra context**
*sessionInfo*
```
```
*package - versie*
resultaat van `utils::packageVersion("fistools")`

**Checklist**
- [x] corrigeer bug
- [x] voer `devtools::check()` uit in de console
- [x] los eventuele errors, warnings en notes<sup>1</sup> op
- [x] increment versie dmv `usethis::use_version(which = "patch")`<sup>2</sup>
- [x] maak een pull request met @soriadelva of @SanderDevisscher en eventueel andere relevante gebruikers als reviewer.

*<sup>1</sup>in de mate van het mogelijke*

*<sup>2</sup>Indien het nodig is om de functie grotendeels te herzien (bvb tgv een depricated package) om de bug op te lossen of als er meerdere functies en/of datasets bij betrokken zijn, gebruik: `usethis::use_version(which = "minor")`. *

**Comment by RuttenAnneleen** [comment]
`> download_gdrive_if_missing(gfileID = "1tSQEdPrF2U7eJg1q5uFnK8lib8t_vXQu",
+                            destfile = "./Projecten/Wilddetectiesysteem_N76/Input/Agouti",
+                            update_always = TRUE)
[1] "extracting email from System variables"
Error in `map()`:
ℹ In index: 1.
Caused by error in `.f()`:
! Client error: (403) Forbidden
Request had insufficient authentication scopes.
PERMISSION_DENIED
• message: Insufficient Permission
• domain: global
• reason: insufficientPermissions
Backtrace:
  1. fistools::download_gdrive_if_missing(...)
  2. googledrive::drive_download(...)
       at fistools/R/download_gdrive_if_missing.R:99:5
  4. googledrive:::as_dribble.drive_id(file)
  5. googledrive::drive_get(id = x)
  7. purrr::map(as_id(id), get_one_file_id)
  8. purrr:::map_("list", .x, .f, ..., .progress = .progress)
 12. googledrive (local) .f(.x[[i]], ...)`

**Comment by SanderDevisscher** [comment]
Vermoedelijk kan de issue opgelost worden door de volgende stappen te doorlopen:
1. run `googledrive::drive_auth()` in the console
2. choose option 1 Send me to the browser for a new auth process. => a browser tab should open now
3. select your email 
4. click continue
5. make sure "show, modify and delete all drive files" is selected
6. click continue
7. continue your R - flow
